baseURL = "https://afolabi.cloudhaven.work"
title = "Cloudhaven"
theme = "PaperMod"

[markup.goldmark.renderer]
  unsafe = true

[pagination]
  pagerSize = 20

# recommended
enableRobotsTXT = true
buildDrafts   = false
buildFuture   = false
buildExpired  = false

[params]
  ShowBreadCrumbs = false
  ShowPostNavLinks = false
  ShowReadingTime = false
  ShowCodeCopyButtons = true

  ShowPostsOnHomePage = false
  defaultTheme = "light"
  disableThemeToggle = true

  [params.profileMode]
    enabled     = false
    title       = "Hi, I'm Bazit ðŸ‘‹"
    subtitle    = "AI/DevOps/SRE â€¢ Building Cloudhaven"
    imageUrl    = "img/image0.jpg"
    imageTitle  = "Bazit headshot"
    imageWidth  = 300
    imageHeight = 300

  [params.label]
  text = ""                      # leave empty if you want only the icon
  icon = "icons/logo.png"        # file at static/icons/logo.png
  iconHeight = 28


  # [[params.profileMode.buttons]]
  #   name = "Resume"
  #   url  = "/resume/"

  # [[params.profileMode.buttons]]
  #   name = "Blog"
  #   url  = "/posts/"

  # [[params.socialIcons]]
  #   name = "github"
  #   url  = "https://github.com/Cloudhaven-IDP"

  # [[params.socialIcons]]
  #   name = "linkedin"
  #   url  = "https://www.linkedin.com/in/afolabifaj/"

# Only menu items we want
[[menu.main]]
  name = "Blog"
  url  = "/posts/"
  weight = 5

[[menu.main]]
  name = "Search"
  url  = "/search/"
  weight = 10

# Keep taxonomies so posts can have tags (no separate menu link)
[taxonomies]
  tag = "tags"
  category = "categories"

# Needed for PaperMod search (builds /index.json)
[outputs]
  home = ["HTML", "RSS", "JSON"]
